### ISSUE TITLE
Add libraries

### ISSUE THREAD

**Issue by mikestreety** [liquidlight/typo3-gallery#2]
@joaoliquidlight and I talked about what libraries should be included:

- [x] Fancybox
- [x] Fancybox Carousel
- [x] Basic (as is)
- [x] AJAX? (where images are put in a JSON/JavaScript array

**Comment by joaoliquidlight** [comment]
done in https://github.com/liquidlight/typo3-gallery/commit/27c5fadbac65f564fa241801dbb9113e058cd32f
